### ISSUE TITLE
plugin.yaml 0.1.5 ref

### ISSUE THREAD

**Issue by jerCarre** [aquasecurity/trivy-plugin-referrer#18]
In plugin.yaml file of 0.2.0, we can find references to 0.1.5

**Comment by knqyf263** [comment]
Contributions welcome

**Comment by jerCarre** [comment]
Herllo,

ok for contribution but what's the next release number ? 0.2.1 ?

Thx

**Comment by knqyf263** [comment]
It will be 0.2.1 after this change.
https://github.com/aquasecurity/trivy-plugin-referrer/issues/17
