### ISSUE TITLE
trivy referrer put fails with SBOM generated by trivy 0.49

### ISSUE THREAD

**Issue by javafrog** [aquasecurity/trivy-plugin-referrer#28]
With trivy 0.49, the structure of the SBOM was changed: https://github.com/aquasecurity/trivy/pull/5981
The current version of the referrer plugin cannot upload SBOM files generated by trivy 0.49, but produces an error:
> Error: error putting referrer: error getting referrer: error processing SBOM: error decoding SBOM: failed to decode: CycloneDX decode error: CycloneDX decode error: json: cannot unmarshal object into Go struct field Metadata.metadata.tools of type []cyclonedx.Tool

As we use a Gitlab pipeline which automatically uses the latest version of trivy for dependency scanning, we can no longer use the referrer plugin to upload these SBOM files.

**Comment by knqyf263** [comment]
Bumping the Trivy version may help.
https://github.com/aquasecurity/trivy-plugin-referrer/blob/1f77b723e3fd47f4c13dc7c66d6d8740b5161ef1/go.mod#L7

**Comment by knqyf263** [comment]
v0.3.1 is out
